# Generated by Django 5.1.2 on 2024-10-30 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_name",
                        message="Допускаются только буквы латиницы и кириллицы",
                        regex="^[a-zA-Zа-яА-Я\\s]*$",
                    )
                ],
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Допускаются только буквы и пробел",
                        regex="^[а-яА-ЯёЁa-zA-Z]+(?:\\s[а-яА-ЯёЁa-zA-Z]+)*$",
                    )
                ],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="meet",
            name="title",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Допускаются только буквы и пробел",
                        regex="^[а-яА-ЯёЁa-zA-Z]+(?:\\s[а-яА-ЯёЁa-zA-Z]+)*$",
                    )
                ],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="meetparticipant",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Присутствует"),
                    ("ABSENT", "Отсутствует"),
                    ("WARNED", "Предупредил"),
                ],
                default="PRESENT",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Допускаются только буквы и пробел",
                        regex="^[а-яА-ЯёЁa-zA-Z]+(?:\\s[а-яА-ЯёЁa-zA-Z]+)*$",
                    )
                ],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="color",
            field=models.IntegerField(
                help_text="Введите цвет в формате 6 цифр.",
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_color",
                        message="Цвет должен состоять из 6 цифр.",
                        regex="^\\d{6}$",
                    )
                ],
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Допускаются только буквы и пробел",
                        regex="^[а-яА-ЯёЁa-zA-Z]+(?:\\s[а-яА-ЯёЁa-zA-Z]+)*$",
                    )
                ],
                verbose_name="Название",
            ),
        ),
    ]
