# Generated by Django 5.1.2 on 2024-11-06 20:00

import django.core.validators
import src.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.CharField(max_length=255, verbose_name="Ссылка"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Активна", "Активна"),
                            ("Использована", "Использована"),
                            ("Срок истёк", "Срок истёк"),
                        ],
                        default="Активна",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        verbose_name="Дата до которой валидна"
                    ),
                ),
            ],
            options={
                "verbose_name": "Приглашение",
                "verbose_name_plural": "Приглашения",
                "db_table": "invite",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_name",
                        message="Допускаются только буквы латиницы и кириллицы",
                        regex="^[a-zA-Zа-яА-Я\\s]*$",
                    )
                ],
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="meet",
            name="title",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Допускаются только буквы и пробел",
                        regex="^[а-яА-ЯёЁa-zA-Z]+(?:\\s[а-яА-ЯёЁa-zA-Z]+)*$",
                    )
                ],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(
                max_length=20,
                validators=[
                    src.validators.validators.ModelValidator.validate_letters_only
                ],
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="color",
            field=models.CharField(
                help_text="Введите цвет в формате 6 цифр.",
                max_length=6,
                validators=[
                    src.validators.validators.ModelValidator.validate_color
                ],
                verbose_name="цвет",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                help_text="Введите название роли до 20 символов(допускаются только буквы кириллицы и латиницы.",
                max_length=20,
                validators=[
                    src.validators.validators.ModelValidator.validate_letters_only
                ],
                verbose_name="название",
            ),
        ),
    ]
