# Generated by Django 5.1.2 on 2024-11-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_alter_features_date_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="features",
        ),
    ]
