# Generated by Django 5.1.2 on 2024-11-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0003_remove_task_features"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
