# Generated by Django 5.1.4 on 2025-01-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=255, verbose_name="Ссылка")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Активна", "Активна"),
                            ("Использована", "Использована"),
                            ("Срок истёк", "Срок истёк"),
                        ],
                        default="Активна",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(verbose_name="Дата до которой валидна"),
                ),
            ],
            options={
                "verbose_name": "Приглашение",
                "verbose_name_plural": "Приглашения",
                "db_table": "invite",
            },
        ),
    ]
