# Generated by Django 5.1.5 on 2025-02-04 09:55

import src.models.invites
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="expires_at",
            field=models.DateTimeField(
                default=src.models.invites.ten_days_from_now,
                verbose_name="Дата до которой валидна",
            ),
        ),
    ]
